WebXDAO/WebXDAO.github.io

- .github/pull_request_template.md
- Improve the pull request template.
> feat: Improve the pull request template

- CODE_OF_CONDUCT.md
- Add Contributor Covenant Code of Conduct v2.1
> Add Contributor Covenant Code of Conduct v2.1

- index.html
N/A
Closes: # 
I added URL of start-here repository at button and remove `active` text in navbar and change it to `Home` text.
> feat: add URL at button and remove active in navbar

- index.html
- Fix minor spelling typo.
This is just a minor spelling typo so I don't think it's needed as it can be easily seen in the Git diff. 🙂
> fix: minor spelling typo

- index.html
- Implement changes from a pending review.
> [feat/fix]: Implement changes from a pending review

- index.html
> add a emoji in footer

- index.html
- styles.css
Closes #17
- Make the cards clickable.
- In the future, we can make those cards redirect to another site.
> feat: make the cards clickable

- index.html
> docs: set the Learn to uppercase

- index.html
> feat: ⚙ Removed underline on Explore button(#28)

- index.html
Closes: #27 
I make each cards clickable instead of the parent section + remove unused code.
> fix: make each cards clickable instead of parent section

- index.html
> BLOG added in the navbar web3community#33

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
> feat: Add basic issue forms

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
- .github/pull_request_template.md
Added checkbox for our code_of_conduct
Not Applicable here
> Update issue templates and PR template

- package-lock.json
- src/_includes/partials/footer.html
- src/index.html
- Make Website Responsive
Closes: #21
Fixed hero section, blockchain developer path, dev protocol brand images and testimonial cards
> Make Website Responsive

- src/_includes/partials/navbar.html
- tailwind.config.js
Closes: #49 
added Animation to the Hamburger icon.
I tested the functionality of my changes on the browser by running the project.
> Add hamburger icon animation

- src/_includes/partials/footer.html
- Update social media text to `Socials`.
- That's shorter; plus, it makes it look better IMO.
> fix: Update social media text to `Socials`

- src/blog/index.html
Closes: #79 
Added 3 tailwindcss flexbox classes to push the author line to the bottom of the card
Ran locally and saw the desired effect
> Push date/author to the bottom of blog card

- CODE_OF_CONDUCT.md
- src/_includes/partials/footer.html
- Update mail to the correct/new one.
> fix: Update mail to the correct/new one

- .gitpod.yml
- README.md
- package-lock.json
- Setup the Gitpod ready-to-code system.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/122"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: Setup the Gitpod ready-to-code system

- src/moderators/index.html
Closes: # 
Replace lorem with actual details
On localhost
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> add moderators-details

- src/moderators/index.html
Closes: # 
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: image not rounded

- src/moderators/index.html
- Fix Krish Gupta's moderator card.
Tested with Gitpod.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/126"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: Krish Gupta's moderator card

- .gitpod.yml
- Fix on-open Gitpod port.
Tested by opening Gitpod on this branch; works.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/128"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: on-open Gitpod port

- src/community/index.html
- Add Dev Protocol's information to the community partners page.
Tested with Gitpod.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/127"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: Add Dev Protocol's information to the community partners page

- src/_includes/partials/footer.html
- Update socials' title.
Tested using Gitpod; works.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/129"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore: Update socials' title

- src/index.html
- Fix doubled phrase.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/135"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: doubled phrase

- src/_includes/partials/footer.html
- Fix the blog link in the footer.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/137"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: update blog link in the footer

- src/_includes/default.html
- Improve SEO.
This has been tested and resources were taken from https://ahrefs.com/blog/open-graph-meta-tags/. All working well.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/140"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: Improve SEO

- src/_includes/default.html
- Add Twitter Meta tags.
Resources taken from https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/141"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: Add Twitter Meta tags

- src/_includes/blog.html
- src/_includes/community.html
- src/_includes/faq.html
- src/_includes/moderators.html
- src/_includes/projects.html
- Add `Web3 Community` to all page titles.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/142"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: add `Web3 Community` to all page titles

- src/moderators/index.html
Closes: #143
Fixed the typo in class attribute of social icons. (`fa` --> `fab`)
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/144"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> FIX: Moderator social icons

- package-lock.json
- src/community/index.html
- tailwind.config.js
I have enabled the hover variant in tailwind.config.js file for the zIndex utilities so that I can add a class `hover:z-10` to all the cards `div` on the community partners page such that they come up of every `div` and not stay behind of any neighbor `div`.
N/A
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/146"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: card stacking in community partners page on hover

- src/_data/navigation.yaml
- src/_includes/partners.html
- src/partners/index.html
- Change `community` to `partners`.
Tested with Gitpod; all working fine.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/147"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore: change `community` to `partners`

- LICENSE
- src/_includes/partials/footer.html
- Update copyright year to 2022.
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/150"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: update copyright year to 2022

- src/_includes/partials/footer.html
Closes: #152 
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/153"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: copyright year at the footer

- src/_includes/blog.html
Closes: https://github.com/web3community/web3community.github.io/issues/154
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/155"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix horizontal scrolling (blog page)

- src/_includes/projects.html
Closes: https://github.com/web3community/web3community.github.io/issues/156
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/157"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix horizontal scrolling (projects page)

- src/_includes/partners.html
Closes: # https://github.com/web3community/web3community.github.io/issues/158
<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/159"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix horizontal scrolling (partners page)

- pages/moderators.js
fixes #173
- Update Krish's pfp
Fixes: #173  
- update krish's pfp
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/176"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> update krish's pfp

- README.md
- Update banner to match WebXDAO branding.
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: update banner to match WebXDAO branding

- src/components/Global/Navbar.js
Added a `Link` redirection to homepage.
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/189"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [FIX]: add hompage redirection to navbar logo

- next-seo.config.js
- package-lock.json
- package.json
- src/pages/_app.js
- src/pages/blog.js
- src/pages/index.js
- src/pages/moderators.js
- src/pages/partners.js
- src/pages/projects.js
- Integrated next-seo with the project.
Closes: #202 
Installed next-seo to the project, created a `next-seo.config.js` file to globally add meta tags and og tags, and manually added relevant next-seo configuration in all the pages.
Verified for each page by checking the source of the file, both in IDE & browser.
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/204"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add SEO Optimization

- src/components/Global/Navbar.js
Closes: #194 
I added <a></a> to redirect to '/' (the homepage) when clicking on the WebXDAO Logo.
Example how to mark a checkbox:-
-->
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/201"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Bug] Fixed logo not redirecting to '/' (homepage)

- .github/workflows/deploy-node.yml
Closes: #200 
This was already there @vinzvinci, but there are a few issues, which I fixed.
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/206"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: update auto deployment instructions

- package.json
Closes: #214 
- Added the metadata for `package.json`
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/215"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore: Added Metadata in package.json

- src/pages/blog.js
- tailwind.config.js
Close: #196 
I have change the Blog page... I made this change according to the contributors page theme 
I created a local hosting to test the changes . I tested for various screen ratio to check the responsive
original screenshot | ![image](https://user-images.githubusercontent.com/104062485/193422383-33051333-ec70-4fb9-b3f6-000973103170.png)
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/210"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Hacktoberfest-2022 Update blog page

- src/pages/index.js
Closes: #224 
Added meta data to src/pages/index.js
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/225"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> added meta data

- README.md
Closes: # 
No issue linked, maybe should we open it?
Added a script to display contributors on the readme.
| ![image](https://user-images.githubusercontent.com/50140834/194063292-4d943a82-462b-4ef4-9e7d-fe8ecf6f652b.png) | ![image](https://user-images.githubusercontent.com/50140834/194063212-ad3efaaa-ca60-451d-82e9-b5bfe543ee1b.png) |
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/227"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [FEAT]: add github contributors in the README

- package-lock.json
- src/components/Global/Footer.js
- src/components/Global/Navbar.js
- src/pages/projects.js
- Improving the responsiveness of projects page to enhance the user experience and make the website mobile friendly.
Closes: #216 
- Updated the Projects page to make it responsive.
- Added new tailwind classes wherever required for the mobile view.
- Retained the existing styling of the desktop view. 
- Updated the footer styling in mobile view to make it look more symmetric with all the text aligned and a visible distinction between category headings and actual links.
The project can be run on the local host and then using the browser inbuilt-site inspector, one can check for the responsiveness
<image src="https://user-images.githubusercontent.com/78547746/193584177-fd223e61-57a …
> #216 responsive projects page

- src/components/Global/Footer.js
- src/components/Global/Navbar.js
Closes: # 
Closes #218 
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/235"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> FEAT: Home hyperlink fix

- src/components/Home/AboutSection.js
- src/pages/about-us.js
Closes: #198 [FEATURE] Build an about us page 
Added an about-us page in pages folder
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/220"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add About-us.js

- src/components/Global/Footer.js
- src/components/Global/Navbar.js
Navbar logo is not showing
Closes: #244 
Changed the file name in the Navbar component.
BEFORE:
AFTER:
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/245"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixed the navbar logo bug for small screen

- src/components/Projcts/ RepoCard.js
- src/pages/projects.js
The current projects page's header does not match the blog and contributors page ui.. so i just remove the blue background 
##my change⬇️
I upgrade the repo cards
added fork counter and open issues. and added topic labels
tested by localhost
| 
| 
|
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/249"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update project page

- src/pages/partners.js
Currently the Partners page does not match the ui of the website. So I made some changes...
Closes: #195 
header does not match the blog, project and contributors page ui.. so i just remove the blue background...
The partners card does not match others page's card ui. so i changed according to them
Tested locally...
|
| 
|
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/250"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> partners page UI update

- docker-compose.yaml
- Fix the image naming (after build)
- Fix the wrong-mounted volume
Mount volume error
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/254"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: docker compose file

- package-lock.json
- package.json
- src/components/Global/Footer.js
- src/components/Projcts/ RepoCard.js
- src/pages/blog.js
- Repocard hover is not looking consistent with other pages
- Blog items margin doesn't look okay 
Closes: # 
- [X ] My code follows the guidelines of this project.
- [X ] My changes generate no new warnings.
- [x ] Any dependent changes have been merged and published in downstream modules.
<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/257"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Made a changes on Blog and Repocard

- src/components/Global/Footer.js
- src/components/Global/Navbar.js
- src/components/Home/HeroSection/CallToActionHero.js
- src/components/Home/HeroSection/ContributeButton.js
- src/pages/partners.js
- src/pages/team.js
- Minor website improvements/fixes.
- Add links to a few buttons and such.
- Fix Krish Gupta's profile data.
- Fix broken mail link.
- Add links to each partner's website.
A few things I wanted to add/fix:
- Center the last partner (in this case, The Algorithms).
- Center all the moderators/maintainers on the team page.
If anyone can do this, feel free to work on it by creating a PR (will make an issue for those two soon). 🙂
Tested with Gitpod, works fine.
> [feat/fix]: minor website improvements/fixes

- src/components/Global/Footer.js
- src/components/Home/HeroSection/DiscordButton.js
- Discord Invitation Link Updated
Closes: #270 
> discord invitation link updated

- src/components/Home/AboutSection.js
Closes: #273
Updated the image path and className
|![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/76116523/8398a7d1-2304-492e-af7d-b74ddbc80d95)|![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/76116523/98877ca4-990d-4e9e-8cc2-69e8f6b13098)|
> fix: image on about page

- app/blogs/page.tsx
- app/page.tsx
- components/v1/Global/Blogs.jsx
- components/v1/Global/Footer.js
- components/v1/Global/Navbar.js
- components/v1/Home/AboutSection.js
- components/v1/Home/DeveloperPath.jsx
- components/v1/Home/DevprotocolBrands.jsx
- components/v1/Home/HeroSection/CallToActionHero.js
- components/v1/Home/HeroSection/ContributeButton.js
- components/v1/Home/HeroSection/DiscordButton.js
- components/v1/Home/HeroSection/Hero.js
- components/v1/Home/HeroSection/Hero2.js
- components/v1/Home/Projects.jsx
- components/v1/Home/Testimonials.jsx
- components/v1/Projcts/ RepoCard.js
- Fixed the eslint error which was causing failure of build.
Closes: #308 
Bug fix.
I have fixed the formatting and used next/image where it was not used.
> Fixing ESlint Error

- config/site.ts
> Updating GitHub & Twitter profile links

- next.config.mjs
- package-lock.json
- package.json
Adding scripts :
``` 
"export": "next build && next export",
"prepare": "husky install",
```
Closes: #308 
> Adding export script in package.json

- next.config.mjs
- Incorrect next.confix.mjs because that app is failing
Closes: #332
> fix:next confix file

- app/page.tsx
- components/ui/TopButton.css
- components/ui/TopButton.tsx
- package-lock.json
- package.json
Added the scroll to top nav button at the bottom right corner of the web page.
* Closes: #326 
I have added the scroll to top nav button at the bottom right corner of the web page which scrolls back to the main home page header when clicked.
I have setup the website on my local environment and then run it and tested the changes.
> Added the Scroll to top nav button

- app/page.tsx
- components/containers/Partners.tsx
> Gradient Heading

- components/main-nav.tsx
- components/site-header.tsx
Navbar is not showing up in mobile screens.
Closes: #348 
So since the code doesn't have navbar for mobile i created it.
Addition of mobile navbar
ScreenShot-
[scrnli_25_05_2023_17-18-31.webm](https://github.com/WebXDAO/WebXDAO.github.io/assets/92094765/bb24e4d0-527f-45b2-97b2-6a720186847f)
> #348-mobile navbar fixed

- components/main-nav.tsx
- Fixing Navbar width more than the screen width 
Closes: #367 
> fixing navbar width issue

- app/layout.tsx
- app/page.tsx
- components/Footer.tsx
- components/main-nav.tsx
- components/site-header.tsx
- Adding Footer and ScrollToTop Button to all pages of the website.
Closes: #351 
Moved footer code from the landing page to another component named Footer.
Added Footer Component into `layout.tsx`.
Moved ScrollToTop Component from landing page and added to `layout.tsx`.
Changed Section tag `<section>` into footer tag `<footer>`
I moved the footer and scrollToTop button into `layout.tsx` so that it can be seen on every page of website.
Changed section tag `<section>` to footer tag `<footer>` for footer section.
> Adding footer and scroll to top button on every page

- app/page.tsx
- components/containers/Partners.tsx
- Fixing heading responsive issue
For: #350  
BUG
| <img width="215" alt="Screenshot 2023-05-26 023704" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/6d217106-bddb-41de-86bb-e3319bd62895"> <img width="215" alt="Screenshot 2023-05-26 023704" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/3c702779-7ecd-450f-94b6-1e12feee4d19"> | <img width="225" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/7ae1f88f-1345-4b80-8aea-be7145419627"> <img width="215" alt="Screenshot 2023-05-26 023704" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/3b37be …
> fixing heading responsive issue

- README.md
- this issue will enhanced the readme file with better installation guideline for first time contributors.
Closes: #365  Refactor the Readme.md File
I have had added an extra and crucial information about the node version which the developers have to keep in mind for successfull setup of local dev environment. also added extra descriptive lines on other installation steps.
Changes in Readme File.
> updated the readme file with better installation guidelines

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/other.yml
add checklist with proper validation format
Closes: #393 
```yml
- type: checkboxes
id: terms
attributes:
label: Checklist
description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)
options:
- label: "I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)"
required: true
- label: "I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)"
required: true
- label: "I am willing to work on this issue (optional)"
required: false
- label: "I am a GSSoC'23 contributor"
required: false
```
- There is no error with the file.
|      Original          |      Updated       |
| …
> docs: update issue form templates

- README.md
What would you like to share?
The license badge is linking to the master branch, which has now been renamed to main.
Usually, GitHub redirects to the main branch, but it is always best to link directly to the main branch.
Closes: #404 
Used main in the license badge link
> [OTHER] Used main in the license badge link

- components/site-header.tsx
- package-lock.json
- tailwind.config.js
Previously Cards were going on top while hovering . Now it is fixed . 
Closes: #383 
Now Community Partners cards does not go on top of the navbar . 
| 
https://github.com/WebXDAO/WebXDAO.github.io/assets/85991449/3579d83d-1f76-4a44-a776-f4e8fd3babd7
|
https://github.com/WebXDAO/WebXDAO.github.io/assets/85991449/5af847de-9f21-4aff-b9f7-e49fb4f71b48
|
> fix: z-index issue for card overlay on hover

- components/landing/Partners.tsx
- Link to Lumos Labs website.
- All other partners are linked to their own websites, however, Lumos Labs was linked only to their Twitter. I believe we should link to their website directly so that they can find all of their socials and know about them easier. 🙂
> chore: link to Lumos Labs website

- package.json
> fix: `package.json` meta

- .github/ISSUE_TEMPLATE/config.yml
> Used new Discord invitation link

- README.md
- Add the forking step in `README.md`.
> docs: add the forking step in `README.md`

- components/landing/Main.tsx
- components/site-header.tsx
Closes: #408  
Added margin bottom on site header
> adding gap between navbar and main content

- app/projects/page.tsx
- components/ProjectCard.tsx
- The projects card has different layout of information than the figma file.
- The layout of the projects card with different width breakpoints change the projects card width.
- Fix or update Read More button design.
- Add box shadows based on v3 design.
Closes: #401 
- remade project card component with accordance to V3 Figma Design.
- isolated project card component completely.
- fixed full width of project card on small screens and mid-sized screens.
The Change was tested visually using Chrome Responsive Mode.
| ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/1978ad7b-d50c-4564-9bd2-b99ce32c3508) | ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/ebe20b32- …
> fix: remake project card with reg. to v3 design

- app/teams/page.tsx
- components/TeamCard.tsx
This pull request is to add the page : WebX team page
Closes: #321 
Added two pages , one to display the team page and the other is a person card .
Have tested it on my local development environment
| Initially their was a 404 page | <img width="950" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/94799887/75f30607-49d8-4a54-ae76-3910ed96ae87">
> feat: Added the WebXTeam page

- styles/globals.css
Added a custom scrollbar to the webpage to improve the overall design.
* Closes: #391 
The basic browser scrollbar is changed to a custom theme-based scrollbar to improve the UI/UX of the web page.
I have setup the website on my local environment and then run it and tested the changes.
| <img width="960" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/113239388/410e6838-247d-4207-aec3-dd782f47b9c4"> | <img width="960" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/113239388/4fe4d24b-ad88-4148-bfa7-7fc4165139bf">|
> Added custom scrollbar

- src/app/layout.tsx
- src/components/main-nav.tsx
Closes: #431 
- `app/layout.tsx`
- `components/main-nav.tsx`
[WebXDAO.webm](https://github.com/WebXDAO/WebXDAO.github.io/assets/130365071/ed982a9b-fe69-4eee-82b0-8dd2996b2e88)
> fix bug: errors and warnings

- src/app/projects/page.tsx
Closes: #400  
Added overflow-hidden and w-full (width 100%) which will fix the screen width issue in projects page.
> Exceeding width

- src/components/main-nav.tsx
Closes: #399 
changing placement of hamburger to right
| ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/cc4239ca-a285-4dbe-b550-abf7041e37e4) | ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/565676fc-68de-4556-bb5a-2cbcdfc8860c) |
> changing placement of hamburger to right

- src/components/main-nav.tsx
Closes: #459 
Enhance the profile dropdown functionality to automatically close when the user scrolls or clicks anywhere within the active window, providing a seamless and intuitive user experience.
> adding event listener to close navbar dropdown

- src/app/blogs/page.tsx
- src/app/contributors/page.tsx
- src/app/projects/page.tsx
- src/app/team/page.tsx
Closes: #418 
Adding a title to every page and default title will be `WebXDAO`.
> adding title to every page

- src/components/ContributorCard.tsx
- src/components/TeamCard.tsx
Closes: #497 
- **Added `title, aria-label, rel attributes to Social Links` of Contributors  and Teams Card Pages** 
- **Added `aria-label, title, rel attributes to Social Icons like Twitter, GitHub and Linkedin Links in Teams Card Page`**
- **Added `aria-label, title, rel attributes to Social Icons like GitHub and LaptopCode Links in Contributors Page`**
> update Bugs/Issues for Social Icons in Contributors and Teams Card Pages

- .github/dependabot.yml
Closes: #507 
```yml
version: 2
updates:
- package-ecosystem: 'github-actions'
labels:
- 📦 dependencies
directory: '/' # refers to the location of package.json
commit-message:
prefix: 'chore(deps)'
schedule:
interval: 'daily'
```
> docs: add dependabot workflow with proper conventions

- .github/workflows/close-old-issues.yml
Closes: #513 
- Reference: https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues#creating-the-workflow
- close old issues after 30 days (add a label stale after 16 days) 
- So, please add the label in the repository accordingly
> docs: workflow to close stale issues for 30 days

- .github/labeler-config.yml
- .github/workflows/add-labels-pr.yml
Reference: https://github.com/hoho4190/issue-pr-labeler
Closes: #508 
You can test it here: https://regex101.com/
I am taking two examples, which you must read so that you can properly review the PR.
- `/\bfeat\b/`: This regular expression matches the exact word "feat" with word boundaries (`\b`). It will match strings that contain the word "feat" as a whole word, but not if it's part of another word (e.g., "defeat" or "feature").
- `/feature/i`: This regular expression matches the word "feature" (case-insensitive) anywhere within a string. It will match strings that contain "feature" in any combination of uppercase and lowercase letters (e.g., "Feature", "FEATURE", "feature").
- I have checked issue forms and corresponding labels to properly use the config workflow.
- I have not made …
> feat: add workflow to add labels based on title

- .github/workflows/author-assign-pr.yml
Closes: #521 
- this workflow will assign pr to the author
```yml
name: 'Author Assign'
on:
pull_request_target:
types: [opened, reopened]
permissions:
pull-requests: write
jobs:
assign-author:
runs-on: ubuntu-latest
steps:
- uses: toshimaru/auto-author-assign@v1.6.2
with:
repo-token: '${{ secrets.GITHUB_TOKEN }}' # GITHUB_TOKEN will be used by default
```
> docs: add workflow to assign pr to author

- tsconfig.json
Closes: #510 
- add this in `tsconfig.json`
```json
"noImplicitAny": true,
```
> feat: add noImplicitAny in tsconfig.json

- index.html
Closes #415.
- Redirect to the new/domain website.
- Assuming that the GH page is built upon the `main` branch, this should automatically redirect to `webxdao.xyz`.
Tested on my fork of this repository, works.
> Redirect to the new/domain website

- src/components/Footer.tsx
- src/components/v1/Projcts/_RepoCard.js
Closes: #449
Uses mailto in href to copy the email and redirect the user to the default app for email 
Changes in the Footer.jsx
> feat: add email to redirect on clicking contact

- .github/CODEOWNERS
Closes: #512 
- `@WebXDAO/webx-core` is for all the files, still I have mentioned it differently
@mkubdev @vinzvinci 
Feel free to request the changes, I'm not aware of members so I don't know which developers are active and in which teams.
> chore: update codeowners based on teams and files

- .gitpod.yml
- Use `npm ci` instead of `npm install`.
Tested using Gitpod.
> Use `npm ci` instead of `npm install`

- README.md
- Use Markdown for the contributors' graph in the readme.
- Specify Bash as the used language in the code ticks.
> Use Markdown for the contributors' graph in the readme
